---
title: Stories by Lyra
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: your-email@example.com
description: A blog of stories by my 5 year old.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
